require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'eduChat' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'RNFBFirestore', :path => '../node_modules/@react-native-firebase/firestore'

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  pod 'RNFBDatabase', :path => '../node_modules/@react-native-firebase/database'

  pod 'react-native-dialogflow', :path => '../node_modules/react-native-dialogflow'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  target 'eduChatTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'eduChat-tvOS' do
  # Pods for eduChat-tvOS

  target 'eduChat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
